make strndup obligatory
resurrecting-open-source-projects/scrot pull request #102
Opened 2021-07-23 23:17 UTC by guijan

scrot is an old program but strndup() is standardized by POSIX 2008 and widely adopted. It's time to make it obligatory.

2021-07-24 00:21 UTC, daltomi requested changes

2021-07-24 00:21 UTC, daltomi commented on configure.ac
>  AC_CHECK_FUNCS([getopt_long getsubopt atexit gethostname memset select strchr strdup strerror strpbrk strrchr strtol],,
Please add the function to the required macro.
```bash
configure.ac: warning: missing AC_CHECK_FUNCS([strndup]) wanted by: src/options.c:431
```

2021-07-24 00:53 UTC, daltomi approved these changes

2021-07-24 01:40 UTC, daltomi commented
Thanks @guijan 

Currently the project is in the stage of launching a new `release`(the `master` branch is "busy") so I leave the maintainer @eribertomota  if he wants to merge this PR at the last minute.

Cheers.

2021-07-24 02:15 UTC, guijan commented
uh-oh. I have an important patch that will cause a merge conflict with this one, let's hold off on it for a while then.

2021-07-26 04:04 UTC, guijan commented
Seems a merge conflict is unavoidable now because files involved with this patch were touched for the release. I'm reopening it.

2021-07-26 04:38 UTC, daltomi commented
Ok, let me fix the conflicts via the GitHub web editor.
 I have seen that you forced the commit but it is not necessary.

2021-07-26 04:46 UTC, guijan commented
Double check Christopher R. Nelson's copyright isn't removed. 
I actually have a properly fixed version ready to push but I don't want to cause a mess with both of us touching this PR.

2021-07-26 04:50 UTC, guijan commented
Yes, it looks perfect now.

2021-07-26 04:54 UTC, merged